#!/usr/bin/env Rscript
token <- "B133433FE3971A3F4A2E433FA9A237E6"
url <- "https://redcap.vanderbilt.edu/api/"
formData <- list("token"=token,
                 content='report',
                 format='json',
                 report_id='313230',
                 csvDelimiter='',
                 rawOrLabel='raw',
                 rawOrLabelHeaders='raw',
                 exportCheckboxLabel='false',
                 returnFormat='json'
)
response <- httr::POST(url, body = formData, encode = "form")
result <- httr::content(response)
print(result)

EDC <- redcapConnection(url = "https://redcap.vanderbilt.edu/api/",
                        token = "09B0A6B7F207F51C6F656BAE567FA390", conn, project = 119047)


#!/usr/bin/env Rscript
token <- "09B0A6B7F207F51C6F656BAE567FA390"
url <- "https://redcap.vanderbilt.edu/api/"
formData <- list("token"=token,
                 content='record',
                 action='export',
                 format='json',
                 type='flat',
                 csvDelimiter='',
                 'records[0]'='183',
                 'events[0]'='eligibility_arm_1',
                 'events[1]'='enrollmentbaseline_arm_1',
                 'events[2]'='18month_followup_arm_1',
                 'events[3]'='3year_followup_arm_1',
                 'events[4]'='5year_followup_arm_1',
                 'events[5]'='7year_followup_arm_1',
                 'events[6]'='9year_followup_arm_1',
                 rawOrLabel='raw',
                 rawOrLabelHeaders='raw',
                 exportCheckboxLabel='false',
                 exportSurveyFields='false',
                 exportDataAccessGroups='false',
                 returnFormat='json'
)
response <- httr::POST(url, body = formData, encode = "form")
result2 <- httr::content(response)
print(result2)




